# See https://semantic-release.gitbook.io/semantic-release/usage/configuration
branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - 'main'
  - name: 'beta'
    prerelease: true
  - name: 'betatest'
    prerelease: true
tagFormat: '${version}' # without this, the tag is prefixed with a 'v'
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - path: "@semantic-release/exec"
    generateNotesCmd: "echo test version ${nextRelease.version}"
    prepareCmd: 'echo "test version ${nextRelease.version} ${branch.name} ${commits.length}" > test_version.txt'
  - path: "@semantic-release/npm"
    npmPublish: false
  - path: "@semantic-release/git"
    assets:
      - "CHANGELOG.md"
      - "package.json"
      - "test_version.txt"
    message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
