name: Build Pull Request

on:
  pull_request:
    branches:
      - '*'

concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
   cancel-in-progress: true

jobs:
  build:
    runs-on: [gpu]
    steps:
      - name: Define environment variables
        run: |
          echo IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo TAG=$(echo "PR-${{ github.event.pull_request.number }}") >> $GITHUB_ENV

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

      - name: Pull latest image as cache
        run: docker pull ${{ env.IMAGE_NAME }}:latest

      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          outputs: type=docker,dest=/tmp/esi-shell-${{ env.TAG }}.tar
          cache-to: type=inline

      - name: Save built image for test jobs
        uses: actions/upload-artifact@v4
        with:
          name: esi-shell-${{ env.TAG }}
          path: /tmp/esi-shell-${{ env.TAG }}.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Define environment variables
        run: |
          echo IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo TAG=$(echo "PR-${{ github.event.pull_request.number }}") >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: esi-shell-${{ env.TAG }}
          path: /tmp

      - name: Run tests
        run: |
          docker load --input /tmp/esi-shell-${{ env.TAG }}.tar
          docker run --rm ${{ env.IMAGE_NAME }}:${{ env.TAG }} bash -l -c opticks-info
