name: Release

on:
  push:
    branches:
      - main
      - beta
      - betatest

jobs:
  build-test-release:
    runs-on: [gpu]
    steps:
      - name: Define environment variables
        run: echo IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for Semantic Release to analyze all commits

      - name: Create semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout new release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.semantic.outputs.new_release_git_tag }}

  cleanup:
    runs-on: ubuntu-latest
    needs: build-test-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Delete untagged images
        run: |
          python -m pip install requests
          .github/workflows/delete_untagged.py ${{ secrets.BNLNPPS_ESI_SHELL_PACKAGES_TOKEN }}
